name: CI
env:
  BRANCH: test-branch

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check for branch
        id: check
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{env.BRANCH}}",
            });
      - name: Create branch
        if: steps.check.outcome != 'success'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/heads/${{env.BRANCH}}",
              sha: context.sha
            });
      - name: Update branch
        if: steps.check.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/heads/${{env.BRANCH}}",
              sha: context.sha
            });
