name: CI
env:
  BRANCH: i18n-preview

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check for branch
        id: check
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.getRef({
              owner: context.owner,
              repo: context.repo,
              ref: "heads/${{ env.BRANCH }}",
            });
      - name: Create branch
        if: steps.check.outcome != 'success'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.owner,
              repo: context.repo,
              ref: "refs/heads/${{ env.BRANCH }}",
              sha: context.sha
            })
