name: CI
env:
  I18N_BRANCH: i18n-preview

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.owner,
              repo: context.repo,
              ref: "refs/heads/${{ env.I18N_BRANCH }}"
              sha: context.sha
            })
